const userTypes = {
  SET_USER_GUEST: 'SET_USER_GUEST',
  SET_USER_PARENT: 'SET_USER_PARENT',
  SET_USER_STUDENT: 'SET_USER_STUDENT',
  SET_USER_EMPLOYEE: 'SET_USER_EMPLOYEE',

  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  SEND_RECOVERY_EMAIL: 'SEND_RECOVERY_EMAIL',

  LOGOUT_USER: 'LOGOUT_USER',
};

export { userTypes };
