const userTypes = {
  SET_USER_GUEST: 'SET_USER_GUEST',
  SET_USER_PARENT: 'SET_USER_PARENT',
  SET_USER_STUDENT: 'SET_USER_STUDENT',
  SET_USER_EMPLOYEE: 'SET_USER_EMPLOYEE',
  LOGOUT_USER: 'LOGOUT_USER',
};

export { userTypes };
